services:
  # PostgreSQL database
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: catkin_auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      # mapping to local port 5434 to avoid conflicts with other PostgreSQL instances
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/catkin_auth
    volumes:
      - ./catkin:/app/catkin
    command: poetry run uvicorn catkin.src.app:app --host 0.0.0.0 --port 5000 --reload
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  postgres_data:
