[project]
name = "catkin"
description = "simple auth server for quart"
authors = [{ "name" = "Tyler Matteson", "email" = "tyler@agritheory.com" }]
license = "MIT"
readme = "README.md"
dynamic = ["version", "dependencies", "requires-python"]

[project.scripts]
start = "catkin.src.app:main"
serve = "uvicorn catkin.src.app:app --host 0.0.0.0 --port 5000 --reload"
# init-db = "scripts.init_db:main"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
version = "1.0.0"

[tool.poetry.dependencies]
python = ">=3.12,<3.14"
asyncpg = "^0.30.0"
jinja2 = "^3.1.6"
cryptography = "^45.0.3"
databases = {extras = ["asyncpg"], version = "^0.9.0"}
pyjwt = "^2.10.1"
environs = "^14.2.0"
quart = "^0.20.0"
quart-cors = "^0.8.0"
strawberry-graphql = {extras = ["debug-server"], version = "^0.270.5"}
uvicorn = "^0.34.3"
httpx = "^0.28.1"
